### ISSUE TITLE
Need help in UI

### ISSUE THREAD

**Issue by shidoitsuka** [SMK-Krian-1/kartu-pelajar#2]
Hi, I kind of need help in datatables.js UI
I'm using mdb v5.0 and kind of unable to edit the default datatables.js styles.

You can check it in :
- class route `/{class}`
- validate route `/validate/{class}`

Both above will show data provided by datatables.js

What I currently want to achieve is : 
- Better styling on the datatables.js

How to build and provide the data (since this project is using Indonesian language) : 
1. Clone it
2. Make a database named `data_kartu` in your MySQL
3. Start your mysql
4. Open `config.js` and change the values if necessary (for server, MySQL config, etc)
5. Run `npm run dev`
6. Open up `{host}:{port}` in your browser
7. Click on `Tambah` button which is located at the first card
8. Click and choose the class from dropdown (any)
9. Fill the data, then submit
10. Go back and click `Validasi`
11. Choose the class that you chose previously
12. You get the datatables.

**Comment by Satyagovind** [comment]
Please provide description regarding your issue.

**Comment by shidoitsuka** [comment]
> Please provide description regarding your issue.

Edited! sorry for not providing any notes

**Comment by shidoitsuka** [comment]
hacktoberfest ended <3
